Promocje Web/ViewModels/UploadViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace Promocje_Web.ViewModels
{
    public class UploadViewModel
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public bool IsPrivate { get; set; }

        [Required(ErrorMessage = "Select the media file to upload")]
        public HttpPostedFileBase File { get; set; }
    }
}

Promocje Web/Controllers/CommentsController.cs
using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Hosting;
using System.Web.Http;
using System.Web.Http.Description;
using System.Web.ModelBinding;
using Microsoft.AspNet.Identity;
using Promocje_Web.Models;

namespace Promocje_Web.Controllers
{
    public class CommentsController : ApiController
    {
        //Disable lazy loading and proxy creation to prevent loop reference issues
        private ApplicationDbContext db = new ApplicationDbContext() { Configuration = { LazyLoadingEnabled = false, ProxyCreationEnabled = false } };

        // GET: api/Comments
        public IHttpActionResult GetComments()
        {
            //db.Configuration.LazyLoadingEnabled = false;
            var comm = db.Comments.Include("Video").Include("Parent").Include("Children").Where(c => c.Parent == null);
            //return Json(new { comments = comm});
            /*var json = JsonConvert.SerializeObject(new {comments = comm});

            var response = this.Request.CreateResponse(HttpStatusCode.OK);
            response.Content = new StringContent(json, Encoding.UTF8, "application/json");
            return response;*/

            string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == currentUserId);
            return
                Ok(
                    new
                    {
                        results =
                            new
                            {
                                comments = comm,
                                total_comment = comm.Count(),
                                user =
                                    new
                                    {
                                        user_id = currentUserId,
                                        Fullname = currentUser != null ? currentUser.UserName : null,
                                        Picture = HostingEnvironment.MapPath("~/Content/images/user_blank_picture.png"),
                                        is_logged_in = true,
                                        is_add_allowed = true,
                                        is_edit_allowed = true
                                    }
                            }
                    }
                    );
        }

        // GET: api/Comments/5
        [ResponseType(typeof(Comment))]
        public IHttpActionResult GetComment(int id)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return NotFound();
            }

            return Ok(comment);
        }

        // PUT: api/Comments/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutComment(int id, Comment comment)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != comment.CommentId)
            {
                return BadRequest();
            }

            db.Entry(comment).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CommentExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Comments
        [ResponseType(typeof(Comment))]
        public IHttpActionResult PostComment(Comment comment)
        {
            string currentUserId = User.Identity.GetUserId();
            if (currentUserId == null)
                return Unauthorized();
            /*if(VideoId == null)
                return BadRequest(ModelState);
            comment.VideoId = (int)VideoId;*/
            comment.User = db.Users.FirstOrDefault(x => x.Id == currentUserId);
            comment.PostedDate = DateTime.Now;
            ModelState.Clear();
            TryValidateModel(comment);
            if (!TryValidateModel(comment))
            {
                return BadRequest(ModelState);
            }

            db.Comments.Add(comment);
            db.SaveChanges();

            return Ok(new
            {
                success=true, result = comment
            
            });
            //return CreatedAtRoute("DefaultApi", new { id = comment.CommentId }, comment);
        }

        // DELETE: api/Comments/5
        [ResponseType(typeof(Comment))]
        public IHttpActionResult DeleteComment(int id)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return NotFound();
            }

            db.Comments.Remove(comment);
            db.SaveChanges();

            return Ok(comment);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool CommentExists(int id)
        {
            return db.Comments.Count(e => e.CommentId == id) > 0;
        }

        protected internal bool TryValidateModel(object model)
        {
            return TryValidateModel(model, null /* prefix */);
        }

        protected internal bool TryValidateModel(object model, string prefix)
        {
            if (model == null)
            {
                throw new ArgumentNullException("model");
            }

            ModelMetadata metadata = ModelMetadataProviders.Current.GetMetadataForType(() => model, model.GetType());
            var t = new ModelBindingExecutionContext(new HttpContextWrapper(HttpContext.Current), new System.Web.ModelBinding.ModelStateDictionary());

            foreach (ModelValidationResult validationResult in ModelValidator.GetModelValidator(metadata, t).Validate(null))
            {
                ModelState.AddModelError(validationResult.MemberName, validationResult.Message);
            }

            return ModelState.IsValid;
        }
    }
}

Promocje Web/Controllers/MediaController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using Promocje_Web.Extensions;
using Promocje_Web.Models;
using Promocje_Web.Services;

namespace Promocje_Web.Controllers
{

    public class MediaController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Video()
        {
            return new VideoResult("Media/sintel/vid7.mp4");
        }

        public ActionResult Videos()
        {
            return View();
        }

        public ActionResult Movie()
        {
            return View();
        }

        public ActionResult Mp4()
        {
            return View();
        }


        

        // GET: Media
      
        public ActionResult Index()
        {
            
            var media = db.MediaFiles;
          
            //Appharbor deletes files on every deploy, clean the remaining records
            foreach (var m in media)
            {
                var baseDir = HostingEnvironment.MapPath("~/MediaData/Videos/" + m.Id);
                if (!Directory.Exists(baseDir))
                {
                   
                    MediaFile mediaFile = db.MediaFiles.Find(m.Id);
                    db.MediaFiles.Remove(mediaFile);
                   
                }
            }
            db.SaveChanges();
           // return View();
             return View(media.Where(file => !file.IsBeingConverted).ToList());
        }

        public ActionResult Category(string id)
        {   
            if (id == null)
                return HttpNotFound();

            var data = db.MediaFiles.Where(m => m.Category == id);
           

            return View("Index",data.ToList());
        }

        public ActionResult Search(string id)
        {
            if (id == null)
                return HttpNotFound();

            var data = db.MediaFiles.Where(m => m.Title.Contains(id));


            return View("Index", data.ToList());
        }

        [Route("Media/{id:int}")]
        public ActionResult Display(int id)
        {
            MediaFile mediaFile = db.MediaFiles.Find(id);
            if(mediaFile == null || mediaFile.IsBeingConverted)
                return HttpNotFound();

            var videoParams = ServerTools.VideoParams.GetVideoParams(mediaFile.VideoQuality);
  
            ViewBag.MediaId = id;
            ViewBag.T = mediaFile.Title;
            ViewBag.Description = mediaFile.Description;
            ViewBag.IsHd = mediaFile.IsHd();
            ViewBag.videoParams = videoParams;
            return View();
        }

        // GET: Media/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MediaFile mediaFile = db.MediaFiles.Find(id);
            if (mediaFile == null)
            {
                return HttpNotFound();
            }
            return View(mediaFile);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Upload()
        {
            ViewBag.Category = new SelectList(ServerTools.CategoriesList.List);
            return View();
        }


        //Called asynchronously, returns 200 status for success with redirect link response, 201 status foe error with validation messages
        [HttpPost]
        public ActionResult Upload([Bind(Include = "Title,Description,IsPrivate,Kategoria")]MediaFile mediaFile, HttpPostedFileBase file)
        {

            var isFileValid = file != null && file.ContentLength > 0;

            mediaFile.ApplicationUserId = User.Identity.GetUserId();

            if (!ModelState.IsValid || !isFileValid || !ServerTools.CategoriesList.List.Contains(mediaFile.Category))
            {
               // ViewBag.Kategoria = new SelectList(ServerTools.CategoriesList.List);
 
               // return View(mediaFile);
                var ms = ModelState;
                Response.StatusCode = 400;
                /*var result = JsonConvert.SerializeObject(ModelState.Values);
                return Content(result, "application/json");*/
                var errors = ModelErrorsToDictionary(ModelState); 
                if(!isFileValid)
                    errors.Add("File","File not supported");

                return Json(errors);
            }

            
           
            mediaFile.IsBeingConverted = true;
            db.MediaFiles.Add(mediaFile);
            db.SaveChanges();

            var dir = Server.MapPath("~/MediaData/Videos/" + mediaFile.Id);

            //todo: check if dir exists
            if (!Directory.Exists(dir))
                Directory.CreateDirectory(dir);
                

            var fileName = Path.GetFileName(file.FileName);
            var path = Path.Combine(dir, fileName);
            file.SaveAs(path);

                
            MediaService.ConvertVideo(fileName,mediaFile.Id);

            ViewBag.Info = "Your video was successfully uploaded";

               
            // return RedirectToAction("Pending","Manage");
            Response.StatusCode = 200;
            return Json("Success");
            

            
        }

        private Dictionary<string, string> ModelErrorsToDictionary(ModelStateDictionary ModelState)
        {
            var errorsDictionary = new Dictionary<string, string>();

            if (!ModelState.IsValid)
            {
                
                StringBuilder errors;

                foreach (KeyValuePair<string, ModelState> state in ModelState)
                {

                    if (state.Value.Errors.Count > 0)
                    {

                        errors = new StringBuilder();

                        foreach (ModelError err in state.Value.Errors)
                        {

                            errors.AppendLine(err.ErrorMessage);

                        }

                        errorsDictionary.Add(state.Key, errors.ToString());

                    }

                }
               
            }
            return errorsDictionary;
        }

        // GET: Media/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Media/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,UserId,Title,AssetId,IsPublic")] MediaFile mediaFile)
        {
            if (ModelState.IsValid)
            {
                db.MediaFiles.Add(mediaFile);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(mediaFile);
        }

        // GET: Media/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MediaFile mediaFile = db.MediaFiles.Find(id);
            if (mediaFile == null)
            {
                return HttpNotFound();
            }
            return View(mediaFile);
        }

        // POST: Media/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserId,Title,AssetId,IsPublic")] MediaFile mediaFile)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mediaFile).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(mediaFile);
        }

        // GET: Media/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MediaFile mediaFile = db.MediaFiles.Find(id);
            if (mediaFile == null)
            {
                return HttpNotFound();
            }
            return View(mediaFile);
        }

        // POST: Media/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MediaFile mediaFile = db.MediaFiles.Find(id);
            db.MediaFiles.Remove(mediaFile);
            db.SaveChanges();

            var dir = Server.MapPath("~/MediaData/Videos/" + id);

            //todo: check if dir exists
            if (Directory.Exists(dir))
                Directory.Delete(dir,true);

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        public ActionResult Prog(int id)
        {
            ViewBag.Id = id;
            return View("Progress");
        }

        [HttpPost]
        public ActionResult Progress(List<int> id)
        {
            if(id == null || id.Count == 0)
                return null;
      

            Dictionary<int,double> objects = new Dictionary<int, double>();
            foreach (int i in id)
            {
                if (HttpContext.Cache[i.ToString()] != null)
                    objects[i] = Math.Ceiling((double) HttpContext.Cache[i.ToString()]*100);
                else
                    objects[i] = 0.0;
            }

Promocje Web/Views/Media/Create.cshtml
@model Promocje_Web.Models.MediaFile

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>



<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Promocje Web/Views/Media/Delete.cshtml
@model Promocje_Web.Models.MediaFile

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MediaFile</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationUserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsPrivate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsPrivate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Promocje Web/Views/Media/Display.cshtml
@{
    ViewBag.Title = "Display";
}

<center>
    <h1>@ViewBag.T</h1>
    <br />
    <div id="wrapper">
        <div id="player"></div>
    </div>
    <h5>@ViewBag.Description</h5>
</center>

<div class="comment-container">

</div>	

<script src="~/Scripts/bitdash.min.js"></script>
<script src="~/Scripts/detectmobilebrowser.js"></script>
<script src="http://jwpsrv.com/library/OF57rvwbEeSB7hJtO5t17w.js"></script>

<script type="text/javascript">
    var conf = {
        key: "a688fd4642b4ff1f7fc403315975d07b",
        source: {
            // mpd: "file/sintel.mpd",
            mpd: "@Url.Action("MediaSegment", "File", new {id = @ViewBag.MediaId, filename = "video.mpd"}, Request.Url.Scheme)",
            progressive: "@Url.Action("MediaFile", "File", new {id = @ViewBag.MediaId, filename = "mobile.mp4"}, Request.Url.Scheme)",
            poster: "@Url.Action("MediaFile", "File", new {id = @ViewBag.MediaId, filename = "thumbnail.jpg"}, Request.Url.Scheme)"
        },
        playback: {
            autoplay: true,
            muted: false
        },
        style: {
            width: '640px',
            height: '360px'
        },
        events: {
            onError: function(data) {
                console.error("bitdash error: " + data.code + ": " + data.message);
            },
            onReady: function(obj) {
                console.log(this.getVersion() + ' onReady: ', obj);
            }
        }
    };

    var player;
    if (!isMobileDevice())
        player = bitdash("player").setup(conf);
    else {
        @* var elem = document.getElementById('wrapper');
        elem.innerHTML = "<video width='640' height='360' autoplay>" +
            " <source src='@Url.Action("MediaFile", "File", new {id = @ViewBag.MediaId, filename = "mobile.mp4"}, Request.Url.Scheme)' type='video/mp4'>" +
            "Your browser does not support the video tag." +
            "</video>";
            *@
        jwplayer("player").setup({
            image: "@Url.Action("MediaFile", "File", new {id = @ViewBag.MediaId, filename = "thumbnail.jpg"}, Request.Url.Scheme)",
            sources: [
                {
                file: "@Url.Action("MediaFile", "File", new {id = @ViewBag.MediaId, filename = "mobile.mp4"}, Request.Url.Scheme)"
            }
            @if (@ViewBag.IsHd)
            {
                <text>
                ,{
                file: "@Url.Action("MediaFile", "File", new {id = @ViewBag.MediaId, filename = "mobileHd.mp4"}, Request.Url.Scheme)"
                }
                </text>
            }
            ],
            width: 480,
            height: 240
        });
    }
</script>

@section Styles {
    <link href="~/Content/jquery.comment.css" rel="stylesheet" />
}
@section Scripts {
    <script src="~/Scripts/jquery-ui-1.9.2.custom.min.js"></script>
    <script src="~/Scripts/jquery.autogrow-textarea.js"></script>
    <script src="~/Scripts/jquery.comment.js"></script>
    <script src="~/Scripts/jquery.timeago.js"></script>

    //Load comments
    <script>
    $(document).ready(function () {

        $('div.comment-container').comment({
            title: 'Comments',
            url_get: '@Url.Action("GetComments", "Comments", new { httproute = "" })',
            videoId: @ViewBag.MediaId,
            url_input: '@Url.RouteUrl("DefaultApi", new { httproute = "", controller = "Comments", action = "PostComment" })', //'articles/id/1/comments/input',
            url_delete: 'articles/id/1/comments/delete',
            limit: 10,
            auto_refresh: false,
            refresh: 10000,
            transition: 'slideToggle',
        });

    });
    </script>
}

Promocje Web/Views/Media/Info.cshtml
@{
    ViewBag.Title = "Info";
}

<h3>@ViewBag.Info</h3>

Promocje Web/Views/Media/Manage.cshtml
@model IEnumerable<Promocje_Web.Models.MediaFile>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            Private
        </th>
       
        <th>
            @Html.DisplayNameFor(model => model.Kategoria)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsPrivate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Kategoria)
        </td>
        <td>
            @Html.ActionLink("Delete","Delete", "Media", new { id=item.Id },null)
        </td>
    </tr>
}

</table>

Promocje Web/Views/Media/Upload.cshtml
@model Promocje_Web.Models.MediaFile

@{
    ViewBag.Title = "Upload";
}

<h2>Upload new media</h2>

@using (Html.BeginForm("Upload", "Media", FormMethod.Post, new { enctype = "multipart/form-data", id="f1" }))
{
    <div class="form-horizontal">
        <h4>MediaFile</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Kategoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               
               @Html.DropDownListFor(model => model.Kategoria, (SelectList)ViewBag.Category, "Select category", new { @class = "form-control" })
               @* @Html.DropDownList("KategoriaId", null, new { @class = "form-control" })*@
                @Html.ValidationMessageFor(model => model.Kategoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsPrivate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsPrivate, new { htmlAttributes = new { @style = "margin-left:0;" } })
                    @Html.ValidationMessageFor(model => model.IsPrivate, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Select file to upload", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span style="color: tomato">Warning! Maximum file size is 10 MB!</span>
                
                @* <input type="file" name="file" />*@
                <div class="input-group">
                    <span class="input-group-btn">
                        <span class="btn btn-primary btn-file">
                            Browse… <input type="file" accept="video/*,.3g2,.3gp,.avi,.dvd,.f4v,.flv,.h261,.h263,.h264,.hds,.hls,.hls,.m4v,.mkv,.mov,.mp4,.mpeg,.mpeg1,.mpeg2,.ogg,.swf,.webm,.webm_,.webm_,.webp,.webp_,.webvt " name="file">
                        </span>
                    </span>
                    <input type="text" style="max-width: 315px;" id="filename" class="form-control" readonly="">
                </div>
                @Html.ValidationMessage("File", new { @class = "text-danger" })
                <div id="filewarning" style="color: red; font-weight: bold; margin-top: 10px;"></div>

                <div class="progress" style="max-width: 300px; display: none; margin-top: 20px;">
                    <div id="prog" class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0.1%">
                        0%
                    </div>
                </div>

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input id="sub" type="submit" value="Upload" class="btn btn-default"/>
                <button id="cancel" class="btn btn-primary btn-file" disabled>Cancel</button>
            </div>
        </div>
    </div>

}

@section Scripts {
    @* <script src="~/Scripts/media-upload.js"></script>
        @Scripts.Render("~/bundles/jqueryui")*@
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery.form.js"></script>
    <script>

        //Upload button
        $(document).on('change', '.btn-file :file', function() {
            var input = $(this),
                numFiles = input.get(0).files ? input.get(0).files.length : 1,
                label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
            var size = input.get(0).files[0].size;
            size = (size / (1024 * 1024)).toFixed(2);

            if (size > 10)
                $('#filewarning').html("File is too large!");
            else
                $('#filewarning').html("");
            input.trigger('fileselect', [numFiles, label]);

            $("#filename").val(label + "  " + size + ' MB');

            validateFileInput();
        });





        var validateFileInput = function() {
            if ($('#filename').val() == null || $('#filename').val() == '') {
                var content = '<span for="File" class="">' + 'Select a supported file.' + '</span>';
                $('span[data-valmsg-for="File"]').html(content);
                return false;
            }
            else
                $('span[data-valmsg-for="File"]').html('');
            return true;
        };

      //  $('#filename').bind('input', validateFileInput);

        //Upload progress
        (function() {

            var bar = $('#prog');
            var percent = $('.percent');
            var status = $('#status');

           

            $('#f1').ajaxForm({
                beforeSubmit: function(arr, $form, options) {
                    $form.validate();

                    if (!validateFileInput())
                        return false;

                    if (!$form.valid())
                        return false;
                    $('.progress').css('display', 'block');
                    $('#sub').attr('disabled', 'disabled');
                    $('#cancel').attr('disabled', false);
                },
                beforeSend: function(xhr) {
                    $('#cancel').click(function() {
                        $('#cancel').attr('disabled', 'disabled');
                        $('.progress').css('display', 'none');
                        $('#sub').attr('disabled', false);
                        xhr.abort();
                    });
                },
                uploadProgress: function(event, position, total, percentComplete) {


                    //$(".progress").html(data);
                    $("#prog").attr('aria-valuenow', percentComplete);
                    $("#prog").html(percentComplete + '%');
                    $("#prog").css('width', percentComplete + '%');

                    if(percentComplete>=100)
                        $('#cancel').attr('disabled', 'disabled');
                },

                success: function(data, textStatus, xhr) {
                    var percentComplete = 100;
                    $("#prog").attr('aria-valuenow', percentComplete);
                    $("#prog").html(percentComplete + '%');
                    $("#prog").css('width', percentComplete + '%');

                    //var json = data; //data.success;
                    window.location.replace("@Url.Action("Pending", "Manage")");

                },
                error: function(data, textStatus, xhr) {
                    var json = (data.responseJSON);
                    $.each(json, function(key, value) {
                        //<span for="Description" class="">Pole Description jest wymagane.</span>
                        var content = '<span for="' + key + '" class="">' + value + '</span>';
                        $('span[data-valmsg-for="' + key + '"]').html(content);
                    });
                },
                complete: function(xhr) {

                }
            });

        })();


    </script>
}

Promocje Web/Views/Media/Videos.cshtml
@{
    ViewBag.Title = "Videos";
}

<h2>Videos</h2>

<video width="320" height="240" controls autoplay="autoplay">
    <source src="@Url.Action("Video","Media")" type="video/mp4">
</video>
MediaFiles